version: "3"

services:
  dynamodb-server:
    image: amazon/dynamodb-local
    ports:
      - 8000:8000
    command: ["-jar", "DynamoDBLocal.jar", "-inMemory", "-sharedDb"]

  url:
    build: ./
    env_file: ./.env.docker
    ports:
      - "3001:3001"
    depends_on:
      - dynamodb-server
